# Generated by Django 5.2.4 on 2025-07-18 21:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='ActaAsamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('tipo_asamblea', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria'), ('mixta', 'Mixta')], max_length=20)),
                ('caracter', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('lugar', models.TextField()),
                ('porcentaje_capital_presente', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('convocatoria_omitida', models.BooleanField(default=False)),
                ('fundamento_convocatoria', models.TextField(blank=True)),
                ('presidente', models.CharField(max_length=255)),
                ('secretario', models.CharField(max_length=255)),
                ('escrutador', models.CharField(blank=True, max_length=255)),
                ('comisario', models.CharField(blank=True, max_length=255)),
                ('metodo_votacion_general', models.CharField(choices=[('economica', 'Económica'), ('nominal', 'Nominal'), ('por_accion', 'Por Acción')], default='economica', max_length=20)),
                ('asistentes_json', models.JSONField(blank=True, null=True)),
                ('orden_dia_json', models.JSONField(blank=True, null=True)),
                ('resoluciones_json', models.JSONField(blank=True, null=True)),
                ('nombramientos_json', models.JSONField(blank=True, null=True)),
                ('dividendos_json', models.JSONField(blank=True, null=True)),
                ('delegados_json', models.JSONField(blank=True, null=True)),
                ('anexos_json', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('firmada', 'Firmada')], default='borrador', max_length=20)),
                ('acta_html_cache', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta de Asamblea',
                'verbose_name_plural': 'Actas de Asambleas',
                'ordering': ['-fecha', '-creada_en'],
            },
        ),
    ]
