# Generated by Django 5.2.4 on 2025-07-22 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaSesionConsejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre completo de la sociedad', max_length=255)),
                ('organo', models.CharField(default='Consejo de Administración', editable=False, max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('lugar', models.TextField(help_text='Dirección física o link de Zoom')),
                ('convocatoria_realizada', models.BooleanField(default=True, help_text='Indica si hubo convocatoria formal (si es False, espera anexo_convocatoria)')),
                ('anexo_convocatoria', models.JSONField(blank=True, help_text="[{ 'tipo':'Convocatoria','archivo':'URL o referencia interna' }]", null=True)),
                ('porcentaje_miembros_presentes', models.DecimalField(decimal_places=2, help_text='Porcentaje de consejeros presentes', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metodo_instalacion', models.CharField(choices=[('mayoria', 'Mayoría'), ('unanimidad', 'Unanimidad')], default='mayoria', help_text='Cómo se declaró instalada la sesión', max_length=20)),
                ('presidente', models.CharField(max_length=255)),
                ('secretario', models.CharField(max_length=255)),
                ('asistentes_json', models.JSONField(blank=True, help_text='\n        [\n          { "nombre":"Daniel Martínez", "rol":"Consejero", "presente":true, "remoto":false },\n          { "nombre":"Luis Hernández",  "rol":"Consejero", "presente":true, "remoto":true }\n        ]\n        ', null=True)),
                ('invitados_json', models.JSONField(blank=True, help_text='\n        [\n          { "nombre":"Ángel Nieblas", "cargo":"Contador Público" },\n          { "nombre":"Ramona Sánchez", "cargo":"Invitada" }\n        ]\n        ', null=True)),
                ('orden_dia_json', models.JSONField(blank=True, help_text='\n        [\n          { "numero":1, "titulo":"Perspectivas políticas y económicas",    "descripcion":"" },\n          { "numero":2, "titulo":"Informe Director General y estados fin.", "descripcion":"" }\n        ]\n        ', null=True)),
                ('resoluciones_json', models.JSONField(blank=True, help_text='\n        [\n          { "punto":1, "clave":"Única",  "texto":"Se toma nota…",         "tipo":"toma_nota" },\n          { "punto":2, "clave":"II.1",   "texto":"Se aprueba el informe…","tipo":"aprobacion_informe" }\n        ]\n        ', null=True)),
                ('delegados_json', models.JSONField(blank=True, help_text='\n        [\n          { "nombre":"Alfonso Arellano", "facultades":"Protocolizar el acta" },\n          { "nombre":"Ramona Sánchez",   "facultades":"Cumplir resoluciones" }\n        ]\n        ', null=True)),
                ('anexos_json', models.JSONField(blank=True, help_text='\n        [\n          { "numero":1, "titulo":"Lista de asistencia" },\n          { "numero":2, "titulo":"Convocatoria" },\n          { "numero":3, "titulo":"Presentación Director General" },\n          { "numero":4, "titulo":"CIM Expansión Sol I" }\n        ]\n        ', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('firmada', 'Firmada')], default='borrador', max_length=20)),
                ('html_cache', models.TextField(blank=True, help_text='HTML congelado al firmar/aprobar')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta de Sesión de Consejo',
                'verbose_name_plural': 'Actas de Sesiones de Consejo',
                'ordering': ['-fecha', '-creada_en'],
            },
        ),
    ]
