# Generated by Django 5.2.4 on 2025-07-24 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_actasesionconsejo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_emision', models.CharField(max_length=200, verbose_name='Lugar de emisión')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('acreedor_nombre', models.CharField(max_length=200, verbose_name='Nombre o razón social del Acreedor')),
                ('acreedor_domicilio', models.TextField(verbose_name='Domicilio del Acreedor')),
                ('acreedor_rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC del Acreedor')),
                ('deudor_nombre', models.CharField(max_length=200, verbose_name='Nombre completo del Deudor')),
                ('deudor_domicilio', models.TextField(verbose_name='Domicilio del Deudor')),
                ('deudor_rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC del Deudor')),
                ('deudor_representante', models.CharField(blank=True, max_length=200, verbose_name='Representante legal')),
                ('monto_numeric', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto principal')),
                ('monto_literal', models.CharField(max_length=300, verbose_name='Monto en letras')),
                ('moneda', models.CharField(default='Pesos Mexicanos', max_length=50, verbose_name='Moneda')),
                ('concepto', models.CharField(help_text='Ej. Préstamo personal, colegiaturas, etc.', max_length=200, verbose_name='Concepto del pagaré')),
                ('tipo_pago', models.CharField(choices=[('unico', 'Un solo pago'), ('parcialidades', 'Parcialidades')], max_length=20, verbose_name='Tipo de pago')),
                ('num_pagos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de pagos')),
                ('periodicidad', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('diario', 'Diario')], max_length=20, null=True, verbose_name='Periodicidad')),
                ('lugar_pago', models.CharField(blank=True, max_length=200, verbose_name='Lugar de pago')),
                ('forma_pago', models.CharField(blank=True, help_text='Ej. transferencia, efectivo, cheque', max_length=100, verbose_name='Forma de pago')),
                ('tasa_interes_ordinario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés ordinario (%)')),
                ('base_intereses', models.PositiveIntegerField(default=360, verbose_name='Base de cálculo de intereses (días)')),
                ('tasa_interes_moratorio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés moratorio (%)')),
                ('gastos_admon', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos de administración')),
                ('impuestos', models.CharField(blank=True, max_length=200, verbose_name='Impuestos aplicables')),
                ('prepago_permitido', models.BooleanField(default=False, verbose_name='Permitir prepago')),
                ('dias_aviso_prepago', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días de aviso para prepago')),
                ('condicion_prepago', models.CharField(blank=True, max_length=200, verbose_name='Condición de prepago')),
                ('tiene_garantia', models.BooleanField(default=False, verbose_name='Tiene garantía o aval')),
                ('descripcion_garantia', models.TextField(blank=True, verbose_name='Descripción de la garantía')),
                ('aval_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Aval')),
                ('aval_domicilio', models.TextField(blank=True, verbose_name='Domicilio del Aval')),
                ('eventos_incumplimiento', models.TextField(verbose_name='Eventos de incumplimiento')),
                ('clausula_aceleracion', models.TextField(verbose_name='Cláusula de aceleración')),
                ('jurisdiccion', models.CharField(max_length=200, verbose_name='Jurisdicción')),
                ('ley_aplicable', models.CharField(default='Leyes de los Estados Unidos Mexicanos', max_length=200, verbose_name='Ley aplicable')),
                ('num_paginas', models.PositiveIntegerField(default=1, verbose_name='Número total de páginas')),
                ('anexos', models.TextField(blank=True, verbose_name='Anexos')),
                ('tabla_amortizacion', models.JSONField(blank=True, help_text='Formato: [{"numero": 1, "fecha": "2025-08-01", "capital": 1000.00, "saldo": 9000.00, "costo_admon": 50.00, "iva_costo_admon": 8.00, "interes": 100.00, "iva_interes": 16.00, "total": 1174.00, "estado": "pendiente", "fecha_pago_real": null}]', null=True, verbose_name='Tabla de amortización')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('firmado', 'Firmado'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='borrador', max_length=20, verbose_name='Estado')),
                ('html_cache', models.TextField(blank=True, verbose_name='HTML generado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagaré',
                'verbose_name_plural': 'Pagarés',
                'ordering': ['-fecha_emision', '-fecha_creacion'],
            },
        ),
    ]
