# Generated by Django 5.2.4 on 2025-07-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_pagare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField(help_text='Fecha en que se firma el contrato')),
                ('lugar_contrato', models.CharField(default='Ciudad de México', max_length=100)),
                ('acreditante_razon_social', models.CharField(max_length=200)),
                ('acreditante_forma_legal', models.CharField(default='S.A.P.I. de C.V.', max_length=100)),
                ('acreditante_representante', models.CharField(max_length=200)),
                ('acreditante_deed_constitucion_numero', models.CharField(max_length=50)),
                ('acreditante_deed_constitucion_fecha', models.DateField()),
                ('acreditante_notario_constitucion', models.CharField(max_length=150)),
                ('acreditante_registro_constitucion_folio', models.CharField(max_length=50)),
                ('acreditante_deed_prom_inv_numero', models.CharField(max_length=50)),
                ('acreditante_deed_prom_inv_fecha', models.DateField()),
                ('acreditante_notario_prom_inv', models.CharField(max_length=150)),
                ('acreditante_registro_prom_inv_folio', models.CharField(max_length=50)),
                ('acreditante_deed_poder_numero', models.CharField(max_length=50)),
                ('acreditante_deed_poder_fecha', models.DateField()),
                ('acreditante_notario_poder', models.CharField(max_length=150)),
                ('acreditado_razon_social_original', models.CharField(max_length=200)),
                ('acreditado_deed_constitucion_original_numero', models.CharField(max_length=50)),
                ('acreditado_deed_constitucion_original_fecha', models.DateField()),
                ('acreditado_notario_constitucion_original', models.CharField(max_length=150)),
                ('acreditado_registro_constitucion_original_folio', models.CharField(max_length=50)),
                ('acreditado_deed_denominacion_cambio_numero', models.CharField(max_length=50)),
                ('acreditado_deed_denominacion_cambio_fecha', models.DateField()),
                ('acreditado_notario_denominacion_cambio', models.CharField(max_length=150)),
                ('acreditado_registro_denominacion_cambio_folio', models.CharField(max_length=50)),
                ('acreditado_deed_poder_numero', models.CharField(max_length=50)),
                ('acreditado_deed_poder_fecha', models.DateField()),
                ('acreditado_notario_poder', models.CharField(max_length=150)),
                ('acreditado_resoluciones_unani_fecha', models.DateField(help_text='Fecha de las resoluciones unánimes del consejo')),
                ('monto_credito', models.DecimalField(decimal_places=2, help_text='Monto total del crédito en MXN', max_digits=14)),
                ('monto_credito_texto', models.CharField(help_text='Monto en texto (p.ej. "Nueve millones de pesos 00/100 Moneda Nacional")', max_length=200)),
                ('numero_disposiciones', models.IntegerField(default=3)),
                ('disposicion1_fecha', models.DateField()),
                ('disposicion1_importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disposicion2_fecha', models.DateField()),
                ('disposicion2_importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disposicion3_fecha', models.DateField()),
                ('disposicion3_importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_credito_fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del crédito')),
                ('pagos_intereses_fecha1', models.DateField()),
                ('pagos_intereses_fecha2', models.DateField()),
                ('pagos_intereses_fecha3', models.DateField()),
                ('pago_principal_fecha', models.DateField(help_text='Fecha de pago de principal')),
                ('tasa_interes_ordinaria', models.DecimalField(decimal_places=2, help_text='Tasa anual (%) de interés ordinario', max_digits=5)),
                ('tasa_interes_moratoria', models.DecimalField(decimal_places=2, help_text='Tasa anual (%) de interés moratorio', max_digits=5)),
                ('banco_cuenta_numero', models.CharField(max_length=30)),
                ('banco_nombre', models.CharField(max_length=150)),
                ('banco_titular', models.CharField(max_length=200)),
                ('banco_clabe', models.CharField(max_length=18)),
                ('domicilio_acreditante', models.TextField()),
                ('domicilio_acreditado', models.TextField()),
                ('jurisdiccion', models.CharField(default='Tribunales de la Ciudad de México', max_length=200)),
                ('ley_aplicable', models.CharField(default='Leyes de los Estados Unidos Mexicanos', max_length=200)),
                ('aval_nombre', models.CharField(max_length=200)),
                ('aval_domicilio', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('firmado', 'Firmado'), ('vigente', 'Vigente'), ('vencido', 'Vencido'), ('pagado', 'Pagado')], default='borrador', max_length=20)),
                ('html_cache', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_credito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de Crédito',
                'verbose_name_plural': 'Contratos de Crédito',
                'ordering': ['-fecha_contrato', '-fecha_creacion'],
            },
        ),
    ]
