# Generated by Django 5.2.4 on 2025-07-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_contrato_credito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPrendaAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField(help_text='Fecha de firma del contrato')),
                ('lugar_contrato', models.CharField(help_text='Lugar de firma del contrato', max_length=200)),
                ('numero_fideicomiso', models.CharField(help_text='Número del fideicomiso', max_length=20)),
                ('fecha_fideicomiso', models.DateField(help_text='Fecha de constitución del fideicomiso')),
                ('fecha_aprobacion_proyecto', models.DateField(help_text='Fecha de aprobación del proyecto')),
                ('descripcion_proyecto', models.TextField(help_text='Descripción del proyecto aprobado')),
                ('deudor_nombre', models.CharField(default='Finanzas, S.A.P.I. de C.V.', max_length=200)),
                ('deudor_constitucion_escritura_num', models.CharField(help_text='Número de escritura de constitución', max_length=50)),
                ('deudor_constitucion_fecha', models.DateField(help_text='Fecha de escritura de constitución')),
                ('deudor_constitucion_notario', models.CharField(help_text='Notario y número', max_length=200)),
                ('deudor_constitucion_registro', models.CharField(help_text='Folio en Registro Público', max_length=100)),
                ('deudor_adopcion_sapi_escritura_num', models.CharField(help_text='Escritura de adopción S.A.P.I.', max_length=50)),
                ('deudor_adopcion_sapi_fecha', models.DateField(help_text='Fecha de escritura de adopción S.A.P.I.')),
                ('deudor_adopcion_sapi_notario', models.CharField(max_length=200)),
                ('deudor_adopcion_sapi_registro', models.CharField(max_length=100)),
                ('deudor_representante', models.CharField(help_text='Nombre del apoderado legal', max_length=200)),
                ('acciones_pledged_cantidad', models.BigIntegerField(help_text='Cantidad de acciones pignoradas')),
                ('acciones_pledged_texto', models.CharField(help_text='Texto de las acciones (en palabras)', max_length=200)),
                ('acreedor_nombre', models.CharField(default='Casa de Bolsa, S.A. de C.V.', max_length=200)),
                ('acreedor_constitucion_escritura_num', models.CharField(max_length=50)),
                ('acreedor_constitucion_fecha', models.DateField()),
                ('acreedor_constitucion_notario', models.CharField(max_length=200)),
                ('acreedor_constitucion_registro', models.CharField(max_length=100)),
                ('acreedor_denominacion1_escritura_num', models.CharField(blank=True, max_length=50)),
                ('acreedor_denominacion1_fecha', models.DateField(blank=True, null=True)),
                ('acreedor_denominacion1_notario', models.CharField(blank=True, max_length=200)),
                ('acreedor_denominacion1_registro', models.CharField(blank=True, max_length=100)),
                ('acreedor_denominacion2_escritura_num', models.CharField(blank=True, max_length=50)),
                ('acreedor_denominacion2_fecha', models.DateField(blank=True, null=True)),
                ('acreedor_denominacion2_notario', models.CharField(blank=True, max_length=200)),
                ('acreedor_denominacion2_registro', models.CharField(blank=True, max_length=100)),
                ('acreedor_denominacion3_escritura_num', models.CharField(blank=True, max_length=50)),
                ('acreedor_denominacion3_fecha', models.DateField(blank=True, null=True)),
                ('acreedor_denominacion3_notario', models.CharField(blank=True, max_length=200)),
                ('acreedor_denominacion3_registro', models.CharField(blank=True, max_length=100)),
                ('delegado_fiduciario', models.CharField(help_text='Nombre del delegado fiduciario', max_length=200)),
                ('delegado_fiduciario_escritura_num', models.CharField(max_length=50)),
                ('delegado_fiduciario_fecha', models.DateField()),
                ('delegado_fiduciario_notario', models.CharField(max_length=200)),
                ('delegado_fiduciario_registro', models.CharField(max_length=100)),
                ('fideicomitente_nombre', models.CharField(default='Hotelería, S.A. de C.V.', max_length=200)),
                ('fideicomitente_constitucion_escritura_num', models.CharField(max_length=50)),
                ('fideicomitente_constitucion_fecha', models.DateField()),
                ('fideicomitente_constitucion_notario', models.CharField(max_length=200)),
                ('fideicomitente_constitucion_registro', models.CharField(max_length=100)),
                ('fideicomitente_representante', models.CharField(help_text='Nombre del apoderado legal', max_length=200)),
                ('fideicomitente_rep_escritura_num', models.CharField(max_length=50)),
                ('fideicomitente_rep_fecha', models.DateField()),
                ('fideicomitente_rep_notario', models.CharField(max_length=200)),
                ('fideicomitente_rep_registro', models.CharField(max_length=100)),
                ('domicilio_deudor', models.TextField()),
                ('domicilio_acreedor', models.TextField()),
                ('domicilio_fideicomitente', models.TextField()),
                ('anexo_contrato_promesa', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('anexo_poder_irrevocable', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('firmado', 'Firmado'), ('vigente', 'Vigente'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('html_cache', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_prenda_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de Prenda sobre Acciones',
                'verbose_name_plural': 'Contratos de Prenda sobre Acciones',
                'ordering': ['-fecha_contrato', '-fecha_creacion'],
            },
        ),
    ]
