# Generated by Django 5.2.4 on 2025-07-24 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_convenio_modificatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatutosSociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(help_text='Nombre completo de la sociedad (sin la abreviatura)', max_length=200)),
                ('forma_legal', models.CharField(help_text='Forma legal o abreviatura (p.ej. S.A.P.I. de C.V.), valor dinámico', max_length=100)),
                ('domicilio', models.CharField(help_text='Domicilio social registrado', max_length=200)),
                ('nacionalidad', models.CharField(default='mexicana', help_text='Nacionalidad de la sociedad', max_length=100)),
                ('objeto_social', models.JSONField(help_text='Lista de cláusulas del objeto social')),
                ('duracion_indefinida', models.BooleanField(default=True, help_text='Si la sociedad tiene duración indefinida')),
                ('convenio_admision_extranjeros', models.BooleanField(default=True, help_text='Si los accionistas adoptan el convenio de admisión de extranjeros')),
                ('capital_fijo_monto', models.DecimalField(decimal_places=2, help_text='Monto del capital fijo en M.N.', max_digits=16)),
                ('capital_fijo_texto', models.CharField(help_text='Monto del capital fijo en texto', max_length=200)),
                ('acciones_serie_a', models.BigIntegerField(help_text='Número de acciones de la Serie A (capital fijo)')),
                ('capital_variable_ilimitado', models.BooleanField(default=True, help_text='True si la parte variable del capital es ilimitada')),
                ('clase_acciones', models.JSONField(help_text="Definición de series de acciones: claves 'A','B','P' con sus derechos y limitaciones")),
                ('libro_registro_acciones', models.CharField(default='Libro de Registro de Acciones', help_text='Nombre del libro de registro de acciones', max_length=200)),
                ('derecho_preferencia', models.BooleanField(default=True, help_text='Si los accionistas tienen derecho de preferencia en aumentos de capital')),
                ('procedimiento_transmision', models.TextField(help_text='Descripción del procedimiento de transmisión de acciones')),
                ('periodicidad_asamblea', models.CharField(default='Anual', help_text='Frecuencia de las Asambleas Ordinarias', max_length=100)),
                ('quorum_ordinaria', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de quórum para Asamblea Ordinaria (%)', max_digits=5)),
                ('quorum_extraordinaria', models.DecimalField(decimal_places=2, default=75.0, help_text='Porcentaje de quórum para Asamblea Extraordinaria (%)', max_digits=5)),
                ('num_consejeros', models.PositiveIntegerField(help_text='Número de consejeros propietarios')),
                ('suplentes_permitidos', models.BooleanField(default=True, help_text='Si hay consejeros suplentes')),
                ('num_comisarios', models.PositiveIntegerField(help_text='Número de comisarios titulares')),
                ('comisarios_suplentes', models.BooleanField(default=True, help_text='Si hay comisarios suplentes')),
                ('ejercicio_inicio', models.CharField(default='01/01', help_text='Fecha de inicio del ejercicio social', max_length=20)),
                ('ejercicio_fin', models.CharField(default='31/12', help_text='Fecha de fin del ejercicio social', max_length=20)),
                ('reserva_legal_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje mínimo para el Fondo de Reserva Legal (%)', max_digits=5)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('firmado', 'Firmado'), ('vigente', 'Vigente'), ('modificado', 'Modificado')], default='borrador', max_length=20)),
                ('html_cache', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatutos_sociedad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatutos Sociales',
                'verbose_name_plural': 'Estatutos Sociales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
