# Generated by Django 5.2.5 on 2025-08-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_estatutos_sociedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actasesionconsejo',
            name='abreviatura_sociedad',
            field=models.CharField(default='CAS', max_length=100),
        ),
        migrations.AddField(
            model_name='actasesionconsejo',
            name='ciudad',
            field=models.CharField(default='México', max_length=100),
        ),
        migrations.AddField(
            model_name='actasesionconsejo',
            name='plataforma_remota',
            field=models.CharField(default='Zoom', max_length=100),
        ),
    ]
