# Generated by Django 5.2.5 on 2025-08-23 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_actasesionconsejo_abreviatura_sociedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasesionconsejo',
            name='metodo_instalacion',
            field=models.CharField(blank=True, choices=[('mayoria', 'Mayoría'), ('unanimidad', 'Unanimidad')], default='mayoria', help_text='Cómo se declaró instalada la sesión', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actasesionconsejo',
            name='porcentaje_miembros_presentes',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, help_text='Porcentaje de consejeros presentes', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
