# Generated by Django 5.2.5 on 2025-08-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_actasesionconsejo_metodo_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasesionconsejo',
            name='convocatoria_realizada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='clausula_aceleracion',
            field=models.TextField(blank=True, null=True, verbose_name='Cláusula de aceleración'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='eventos_incumplimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Eventos de incumplimiento'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='jurisdiccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jurisdicción'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='ley_aplicable',
            field=models.CharField(blank=True, default='Leyes de los Estados Unidos Mexicanos', max_length=200, null=True, verbose_name='Ley aplicable'),
        ),
    ]
