# Generated by Django 5.2.5 on 2025-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_alter_actasesionconsejo_convocatoria_realizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagare',
            name='base_intereses',
            field=models.PositiveIntegerField(blank=True, default=360, null=True, verbose_name='Base de cálculo de intereses (días)'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='clausula_aceleracion',
            field=models.TextField(blank=True, default='', verbose_name='Cláusula de aceleración'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='concepto',
            field=models.CharField(blank=True, help_text='Ej. Préstamo personal, colegiaturas, etc.', max_length=200, null=True, verbose_name='Concepto del pagaré'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='eventos_incumplimiento',
            field=models.TextField(blank=True, default='', verbose_name='Eventos de incumplimiento'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='forma_pago',
            field=models.CharField(blank=True, help_text='Ej. transferencia, efectivo, cheque', max_length=100, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='gastos_admon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gastos de administración'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='jurisdiccion',
            field=models.CharField(blank=True, default='Ciudad de México', max_length=200, verbose_name='Jurisdicción'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='ley_aplicable',
            field=models.CharField(blank=True, default='Leyes de los Estados Unidos Mexicanos', max_length=200, verbose_name='Ley aplicable'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='lugar_pago',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de pago'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='moneda',
            field=models.CharField(blank=True, default='Pesos Mexicanos', max_length=50, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='monto_literal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Monto en letras'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='monto_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto principal'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='num_paginas',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Número total de páginas'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='tasa_interes_moratorio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa de interés moratorio (%)'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='tasa_interes_ordinario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa de interés ordinario (%)'),
        ),
        migrations.AlterField(
            model_name='pagare',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('unico', 'Un solo pago'), ('parcialidades', 'Parcialidades')], max_length=20, null=True, verbose_name='Tipo de pago'),
        ),
    ]
