# Generated by Django 5.2.5 on 2025-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_alter_pagare_base_intereses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniomodificatorio',
            name='credito_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del crédito original', max_digits=14, null=True),
        ),
    ]
